name: la_voz_de_la_cura_divina
description: Una aplicación de radio para La Voz de la Cura Divina.
version: 1.0.0+84
environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  just_audio: any
  just_audio_background: any
  audio_service: any
  audio_session: any
  provider: any
  url_launcher: any
  marquee: any
  share_plus: any
  flutter_spinkit: any
  connectivity_plus: any
  loading_animation_widget: any
  google_fonts: any
  intl: any
  sleek_circular_slider: any
  android_alarm_manager_plus: any
  shared_preferences: any
  firebase_core: ^4.6.0
  firebase_remote_config: ^6.3.0
  firebase_messaging: ^16.1.3
  flutter_local_notifications: ^19.5.0
  firebase_analytics: ^12.2.0
  timezone: ^0.10.1
  flutter_inappwebview: ^6.1.5
  firebase_crashlytics: ^5.1.0
  permission_handler: ^11.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
